
import { GoogleGenAI } from "@google/genai";

// Ensure the API key is available, but do not hardcode it.
// It's expected to be set in the environment variables.
if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set.");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generateStrategy = async (businessIdea: string): Promise<string> => {
  const model = "gemini-2.5-flash";
  const prompt = `
    You are an expert business strategist. A user has provided a business idea. 
    Your task is to generate a concise, high-level business strategy for them.

    Business Idea: "${businessIdea}"

    Please structure your response in a clear, readable format with the following sections:

    ## Strategic Plan for Your Business

    ### 1. Market Analysis
    *   **Target Audience:** Identify the primary customer segment.
    *   **Key Competitors:** List 2-3 potential competitors.
    *   **Market Opportunity:** Briefly describe why this idea can succeed in the current market.

    ### 2. Value Proposition
    *   **Problem Solved:** What specific problem does this business solve for the target audience?
    *   **Unique Selling Proposition (USP):** What makes this business different from or better than competitors?

    ### 3. Monetization Strategy
    *   **Revenue Streams:** Suggest 1-2 primary ways the business will make money (e.g., subscription, one-time purchase, ad revenue).

    ### 4. Go-to-Market Channels
    *   **Marketing & Sales:** Suggest 2-3 effective channels to reach the target audience (e.g., social media marketing, content marketing, local partnerships).

    ---

    *Disclaimer: This is a high-level strategic outline generated by AI. For a comprehensive business plan, consult with business professionals and conduct thorough market research.*
  `;

  try {
    const response = await ai.models.generateContent({
      model,
      contents: prompt,
    });
    return response.text;
  } catch (error) {
    console.error("Error generating content from Gemini API:", error);
    throw new Error("Failed to generate strategy. The AI service may be unavailable.");
  }
};
